# Generated by Django 4.0.6 on 2022-08-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_card_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.IntegerField(),
        ),
    ]
