# Generated by Django 4.0.6 on 2022-08-20 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_remove_transaction_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thirdparty',
            name='currency',
        ),
        migrations.AddField(
            model_name='notifications',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='title',
            field=models.CharField(max_length=105, null=True),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='Transaction_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_customer', to='wallet.customer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_receipt', to='wallet.receipts'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_history',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='userId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('Master', 'Mastercard'), ('visa', 'visacard')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='country_of_origin',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nationality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phonenumber',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_Id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='receipt_type',
            field=models.CharField(choices=[('deposits', 'Bank deposits'), ('withdrawals', 'Cash withdrawals'), ('loan', 'loan payments'), ('creditcard', 'creditcard payments')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='recipt_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='total_Amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reward',
            name='bonus',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='thirdparty_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('withdraw', 'Withdrawal'), ('deposit', 'Deposit')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='pin',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
