# Generated by Django 4.0.6 on 2022-08-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_remove_thirdparty_currency_notifications_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='account_name',
        ),
    ]
