# Generated by Django 4.0.6 on 2022-08-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_remove_thirdparty_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thirdparty',
            old_name='Transaction_cost',
            new_name='transaction_cost',
        ),
    ]
