# Generated by Django 4.0.6 on 2022-09-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_alter_wallet_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipts',
            old_name='recipt_File',
            new_name='receipt_File',
        ),
        migrations.RenameField(
            model_name='receipts',
            old_name='recipt_number',
            new_name='receipt_number',
        ),
    ]
